print("module py_main")
import exception_handling as b
print("after py_main")

import sys

VAR_A = 0

def main():
	b.change(12,13)

def a():
    print("inside a")


print('---a---')